### ISSUE TITLE
kibana5 and ark > 2.2.1

### ISSUE THREAD

**Issue by 1971hemicuda** [anuriq/chef-kibana5#14]
We had ark=v3.1.0 installed on our chef server.  When running chef-client we would always receive the error below.  

We had to down grade to ark=v2.2.1 and now this installs.  Might want to check it out

Recipe: kibana5::default
  * kibana5_install[kibana] action install[2017-06-19T08:54:18-05:00] INFO: Processing kibana5_install[kibana] action install (kibana5::default line 19)

    * group[kibana] action create[2017-06-19T08:54:18-05:00] INFO: Processing group[kibana] action create (/var/chef/cache/cookbooks/kibana5/resources/install.rb line 41)
 (up to date)
    * user[kibana] action create[2017-06-19T08:54:18-05:00] INFO: Processing user[kibana] action create (/var/chef/cache/cookbooks/kibana5/resources/install.rb line 43)

      
      ================================================================================
      Error executing action `create` on resource 'user[kibana]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '8'
      ---- Begin output of ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] ----
      STDOUT: 
      STDERR: usermod: user kibana is currently used by process 29479
      ---- End output of ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] ----
      Ran ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] returned 8
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/kibana5/resources/install.rb
      
       43:     user new_resource.svc_user do
       44:       comment 'Kibana User'
       45:       gid new_resource.svc_group
       46:       home new_resource.base_dir
       47:       shell '/bin/bash'
       48:       system true
       49:     end
       50: 
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/kibana5/resources/install.rb:43:in `block in class_from_file'
      
      user("kibana") do
        action [:create]
        supports {:manage_home=>false, :non_unique=>false}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "kibana"
        comment "Kibana User"
        gid 164
        home "/opt/kibana"
        shell "/bin/bash"
        system true
        iterations 27855
        declared_type :user
        cookbook_name "kibana5"
      end
      
[2017-06-19T08:54:18-05:00] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `install` on resource 'kibana5_install[kibana]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    user[kibana] (/var/chef/cache/cookbooks/kibana5/resources/install.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
    ---- Begin output of ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] ----
    STDOUT: 
    STDERR: usermod: user kibana is currently used by process 29479
    ---- End output of ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] ----
    Ran ["usermod", "-c", "Kibana User", "-d", "/opt/kibana", "kibana"] returned 8
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/kibana5/recipes/default.rb
    
     19: kibana5_install 'kibana'
     20: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/kibana5/recipes/default.rb:19:in `from_file'
    
    kibana5_install("kibana") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :kibana5_install
      cookbook_name "kibana5"
      recipe_name "default"
      version "5.4.1"
      install_method "release"
      base_dir "/opt/kibana"
      svc_group "kibana"
      svc_user "kibana"
    end

**Comment by anuriq** [comment]
Hi @1971hemicuda 
I don't see how this is connected to `ark` cookbook. Maybe you were using older version of kibana cookbook, and home folder for user was changed?

**Comment by anuriq** [comment]
Hi @1971hemicuda 
any news there?
