### ISSUE TITLE
service[kibana]: Service is not known to chkconfig

### ISSUE THREAD

**Issue by gsaxam** [anuriq/chef-kibana5#21]
Hi,

I am at a point where kibana is not a service and I could not find its entry inside `/etc/init.d`. What should I do to move on? I only need a default installation of kibana.

> * service[kibana] action enable
>       * service[kibana]: Service is not known to chkconfig.
>       ================================================================================
>       Error executing action `enable` on resource 'service[kibana]'
>       ================================================================================
> 
>       Chef::Exceptions::Service
>       -------------------------
>       service[kibana]: Service is not known to chkconfig.
> 
>       Resource Declaration:
>       ---------------------
>       # In /var/chef/cache/cookbooks/kibana5/resources/configure.rb
> 
>        66:   service new_resource.svc_name do
>        67:     supports start: true, restart: true, stop: true, status: true
>        68:     action [:enable, :start]
>        69:   end
>        70: end
> 
>       Compiled Resource:
>       ------------------
>       # Declared in /var/chef/cache/cookbooks/kibana5/resources/configure.rb:66:in `block in class_from_file'
> 
>       service("kibana") do
>         action [:enable, :start]
>         supports {:start=>true, :restart=>true, :stop=>true, :status=>true}
>         retries 0
>         retry_delay 2
>         default_guard_interpreter :default
>         service_name "kibana"
>         pattern "kibana"
>         declared_type :service
>         cookbook_name "kibana5"
>       end
> 
>       Platform:
>       ---------
>       x86_64-linux
> 
>     * service[kibana] action restart
>       * service[kibana]: No custom command for restart specified and unable to locate the init.d script!
>       ================================================================================
>       Error executing action `restart` on resource 'service[kibana]'
>       ================================================================================
> 
>       Chef::Exceptions::Service
>       -------------------------
>       service[kibana]: No custom command for restart specified and unable to locate the init.d script!

**Comment by TheKatarGit** [comment]
@gsaxam Hi
Could you please tell your platform and its version?

**Comment by anuriq** [comment]
Hi @gsaxam 
Can we close this?
