### ISSUE TITLE
Implement compatibility with Ubuntu 14.04

### ISSUE THREAD

**Issue by catalinvr** [anuriq/chef-kibana5#27]
Hi,

I need this feature implemented to work with my production environment.

Thanks,
Catalin

**Comment by catalinvr** [comment]
Hi @anuriq,

This time I fixed the typos and created new test for Ubuntu 14.04.
Seems that remains to fix this cookbook for Centos 7
When you have time, please can you merge this change.

Thanks,
Cata

**Comment by anuriq** [comment]
Same comment as in https://github.com/anuriq/chef-kibana5/pull/28
