### ISSUE TITLE
Missing the ability to disable xpath auth

### ISSUE THREAD

**Issue by zinefer** [anuriq/chef-kibana5#35]
Great cookbook! Thanks very much for your recent work also.

Since you're active I figured I would post the most recent issue I've run into.

We're running elastic/kibana behind a vpn and firewall so we run without auth. I need to be able to set
`xpack.security.enabled: false` 
in the kibana.yml

**Comment by anuriq** [comment]
I'll check this, thank you

**Comment by TheKatarGit** [comment]
#40

**Comment by TheKatarGit** [comment]
@zinefer I've added the ability to trigger xpack.security.enabled in kibana.yml, although they highly recommend to configure it within elasticsearch config.
