### ISSUE TITLE
kibana5_configure doesn't pick up other settings

### ISSUE THREAD

**Issue by Ellison001** [anuriq/chef-kibana5#49]
Hi,
I create a wrapper cookbook named abc-kibana which depends on kibana5(1.6.5).
when I define attributes in abc-kibana as below, the default kibana5 recipe doesn't set the value for kibana.yml as expected. Please help.

abc-kibana/attributes/default.rb
default['kibana5']['config']['elasticsearch.username'] = 'user1'
default['kibana5']['config']['elasticsearch.password'] = 'pw1'

**Comment by anuriq** [comment]
Hi @Ellison001 

how do you call kibana5 cookbook? could you send that part of code?

**Comment by Ellison001** [comment]
Hi Anuriq,
This issue is due to the kibana5 cookbook's ERB template doesn't pick up those values. I override the ERB template in my wrapper cookbook, the issue is fixed.
BTW: I am using kibana-6.5.4.

**Comment by anuriq** [comment]
@Ellison001 could you clarify that issue is resolved, or there is still a problem?

**Comment by Ellison001** [comment]
The issue is resolved.
